import { db } from './server/db';
import { quizzes, quizQuestions } from './shared/schema';

async function addYouthMinistryFinalExam() {
  try {
    console.log('Creating Youth Ministry Final Exam...');
    
    const [quiz] = await db.insert(quizzes).values({
      id: 212,
      moduleId: null,
      title: 'Youth Ministry — Final Exam',
      timeLimit: 30, // 30 minutes for final exam
      passingScore: 70,
      isFinalExam: true,
      isPublished: true,
      publishedAt: new Date(),
    }).returning();
    
    const questions = [
      { quizId: 212, question: 'Samuel\'s first response to God\'s call models which core posture?', type: 'multiple_choice' as const, options: ['A) Strategic planning', 'B) Listening obedience', 'C) Platform building', 'D) Skeptical testing'], correctAnswer: 'B) Listening obedience', points: 1, orderIndex: 1 },
      { quizId: 212, question: 'David\'s anointing teaches that God primarily looks at:', type: 'multiple_choice' as const, options: ['A) Appearance', 'B) Achievement', 'C) Heart', 'D) Heritage'], correctAnswer: 'C) Heart', points: 1, orderIndex: 2 },
      { quizId: 212, question: 'A biblically healthy understanding of calling includes:', type: 'multiple_choice' as const, options: ['A) Role before identity', 'B) Identity in Christ, holy character, and specific assignment', 'C) Emotions over evaluation', 'D) Platform before people'], correctAnswer: 'B) Identity in Christ, holy character, and specific assignment', points: 1, orderIndex: 3 },
      { quizId: 212, question: 'The most reliable confirmation of a ministry call includes:', type: 'multiple_choice' as const, options: ['A) Viral attention', 'B) Conference emotion', 'C) External church affirmation and observable fruit over time', 'D) Personal passion alone'], correctAnswer: 'C) External church affirmation and observable fruit over time', points: 1, orderIndex: 4 },
      { quizId: 212, question: 'According to Tony Evans, preaching carries authority because it is:', type: 'multiple_choice' as const, options: ['A) Culturally trendy', 'B) Personality-driven', 'C) Word-centered and Spirit-empowered', 'D) Crowd-approved'], correctAnswer: 'C) Word-centered and Spirit-empowered', points: 1, orderIndex: 5 },
      { quizId: 212, question: 'Maxwell\'s Law of the Process teaches leadership grows:', type: 'multiple_choice' as const, options: ['A) Only in crises', 'B) After ordination', 'C) Daily, not in a day', 'D) Automatically with age'], correctAnswer: 'C) Daily, not in a day', points: 1, orderIndex: 6 },
      { quizId: 212, question: 'Timothy was told to counter youth-related criticism by:', type: 'multiple_choice' as const, options: ['A) Demanding respect', 'B) Avoiding hard topics', 'C) Setting an example in speech, conduct, love, faith, purity', 'D) Changing churches'], correctAnswer: 'C) Setting an example in speech, conduct, love, faith, purity', points: 1, orderIndex: 7 },
      { quizId: 212, question: 'The fear of the Lord chiefly produces:', type: 'multiple_choice' as const, options: ['A) Novelty seeking', 'B) Motive purification and obedient living', 'C) Audience focus', 'D) Risk avoidance'], correctAnswer: 'B) Motive purification and obedient living', points: 1, orderIndex: 8 },
      { quizId: 212, question: 'Calling discernment ripens best through:', type: 'multiple_choice' as const, options: ['A) Isolation', 'B) Mentoring and community testing', 'C) Self-affirmation', 'D) Brand building'], correctAnswer: 'B) Mentoring and community testing', points: 1, orderIndex: 9 },
      { quizId: 212, question: 'Rooting identity in role rather than in Christ will most likely produce:', type: 'multiple_choice' as const, options: ['A) Steady peace', 'B) Rollercoaster living and fragile ministry', 'C) Deeper humility', 'D) Clearer priorities'], correctAnswer: 'B) Rollercoaster living and fragile ministry', points: 1, orderIndex: 10 },
      { quizId: 212, question: 'The first requirement of spiritual leadership is:', type: 'multiple_choice' as const, options: ['A) Innovation', 'B) Influence', 'C) Character above reproach', 'D) Capacity'], correctAnswer: 'C) Character above reproach', points: 1, orderIndex: 11 },
      { quizId: 212, question: 'A rule of life primarily helps you:', type: 'multiple_choice' as const, options: ['A) Automate relationships', 'B) Maintain a living connection with Christ', 'C) Grow social media presence', 'D) Plan more events'], correctAnswer: 'B) Maintain a living connection with Christ', points: 1, orderIndex: 12 },
      { quizId: 212, question: 'Relational credibility with students is earned through:', type: 'multiple_choice' as const, options: ['A) Clever branding', 'B) Consistent presence, empathy, and reliability', 'C) Frequent rule changes', 'D) High-energy events'], correctAnswer: 'B) Consistent presence, empathy, and reliability', points: 1, orderIndex: 13 },
      { quizId: 212, question: 'A text-driven sermon means:', type: 'multiple_choice' as const, options: ['A) A story with a verse attached', 'B) The passage\'s main point drives the message\'s main point', 'C) Application-free "depth"', 'D) Topic-only monologue'], correctAnswer: 'B) The passage\'s main point drives the message\'s main point', points: 1, orderIndex: 14 },
      { quizId: 212, question: 'Maxwell\'s Law of the Lid implies leaders should:', type: 'multiple_choice' as const, options: ['A) Resist growth to retain control', 'B) Grow character and capacity to raise impact', 'C) Delegate everything immediately', 'D) Focus solely on numbers'], correctAnswer: 'B) Grow character and capacity to raise impact', points: 1, orderIndex: 15 },
      { quizId: 212, question: 'Healthy boundaries in student ministry include:', type: 'multiple_choice' as const, options: ['A) Private, uninterruptible meetings', 'B) Two-adult rule and observable, interruptible settings', 'C) Disappearing messages', 'D) No documentation ever'], correctAnswer: 'B) Two-adult rule and observable, interruptible settings', points: 1, orderIndex: 16 },
      { quizId: 212, question: 'Emotional resilience grows through:', type: 'multiple_choice' as const, options: ['A) Ignoring feelings', 'B) Shame-driven effort', 'C) Rhythms of rest, honest support, and wise habits', 'D) More late-night work'], correctAnswer: 'C) Rhythms of rest, honest support, and wise habits', points: 1, orderIndex: 17 },
      { quizId: 212, question: 'Financial integrity is best shown by:', type: 'multiple_choice' as const, options: ['A) Loose records', 'B) Cash-only with no receipts', 'C) Receipts and approved processes', 'D) Personal discretion funds'], correctAnswer: 'C) Receipts and approved processes', points: 1, orderIndex: 18 },
      { quizId: 212, question: 'Cultural wisdom looks like:', type: 'multiple_choice' as const, options: ['A) Mimicking student platforms', 'B) Teaching digital discipleship and trauma-informed care', 'C) Avoiding safety policies', 'D) Debating online'], correctAnswer: 'B) Teaching digital discipleship and trauma-informed care', points: 1, orderIndex: 19 },
      { quizId: 212, question: 'Aligning youth ministry with the church means:', type: 'multiple_choice' as const, options: ['A) Running an independent mission', 'B) Competing for authority', 'C) Coordinating vision, teaching, and calendar with leaders', 'D) Avoiding feedback'], correctAnswer: 'C) Coordinating vision, teaching, and calendar with leaders', points: 1, orderIndex: 20 },
      { quizId: 212, question: 'A sustainable weekly rhythm protects:', type: 'multiple_choice' as const, options: ['A) Only admin time', 'B) Only emergency time', 'C) Time with God, students, team, preparation, admin, and rest', 'D) Last-minute prep alone'], correctAnswer: 'C) Time with God, students, team, preparation, admin, and rest', points: 1, orderIndex: 21 },
      { quizId: 212, question: 'Effective student preaching begins with:', type: 'multiple_choice' as const, options: ['A) Trend scanning', 'B) Story gathering', 'C) Praying and letting the text shape the preacher', 'D) Picking multiple big ideas'], correctAnswer: 'C) Praying and letting the text shape the preacher', points: 1, orderIndex: 22 },
      { quizId: 212, question: 'In small groups, the priority is:', type: 'multiple_choice' as const, options: ['A) Unstructured hangouts only', 'B) Lecture-only monologues', 'C) Scripture engagement and real-life application in a safe environment', 'D) Constant leader rotation'], correctAnswer: 'C) Scripture engagement and real-life application in a safe environment', points: 1, orderIndex: 23 },
      { quizId: 212, question: 'A basic small group leader weekly tool should include:', type: 'multiple_choice' as const, options: ['A) Ten pages of notes', 'B) A concise big idea, 3–5 questions, and two follow-ups', 'C) Only a video link', 'D) No guidance at all'], correctAnswer: 'B) A concise big idea, 3–5 questions, and two follow-ups', points: 1, orderIndex: 24 },
      { quizId: 212, question: 'A best practice for first-time guest follow-up is:', type: 'multiple_choice' as const, options: ['A) Wait for a month', 'B) Send a mass newsletter', 'C) Warm personal contact within 48 hours with a clear next step', 'D) Contact only if they return'], correctAnswer: 'C) Warm personal contact within 48 hours with a clear next step', points: 1, orderIndex: 25 },
      { quizId: 212, question: 'Pastoral crisis care starts with:', type: 'multiple_choice' as const, options: ['A) Lecturing', 'B) Public prayer posts', 'C) Listening, praying, and involving parents/pastors appropriately', 'D) Promising total secrecy'], correctAnswer: 'C) Listening, praying, and involving parents/pastors appropriately', points: 1, orderIndex: 26 },
      { quizId: 212, question: 'Partnering with parents looks like:', type: 'multiple_choice' as const, options: ['A) Replacing them', 'B) Competing for influence', 'C) Clear communication and resourcing faith at home', 'D) Avoiding contact'], correctAnswer: 'C) Clear communication and resourcing faith at home', points: 1, orderIndex: 27 },
      { quizId: 212, question: 'Volunteer development moves from doer to developer when you:', type: 'multiple_choice' as const, options: ['A) Keep control of all tasks', 'B) Recruit to fill gaps only', 'C) Train, coach, and entrust real ownership', 'D) Avoid feedback'], correctAnswer: 'C) Train, coach, and entrust real ownership', points: 1, orderIndex: 28 },
      { quizId: 212, question: 'Wise administration asks:', type: 'multiple_choice' as const, options: ['A) What\'s trendiest?', 'B) What impresses other churches?', 'C) Does this help us make disciples?', 'D) How fast can we spend?'], correctAnswer: 'C) Does this help us make disciples?', points: 1, orderIndex: 29 },
      { quizId: 212, question: 'Metrics that matter emphasize:', type: 'multiple_choice' as const, options: ['A) Attendance only', 'B) Merchandise sales', 'C) Engagement, follow-up, small groups, next steps, leader health', 'D) Stage design updates'], correctAnswer: 'C) Engagement, follow-up, small groups, next steps, leader health', points: 1, orderIndex: 30 },
      { quizId: 212, question: 'Accountability\'s purpose is to:', type: 'multiple_choice' as const, options: ['A) Control people', 'B) Avoid conflict', 'C) Create conditions for truth, trust, and healthy growth', 'D) Impress outsiders'], correctAnswer: 'C) Create conditions for truth, trust, and healthy growth', points: 1, orderIndex: 31 },
      { quizId: 212, question: 'A Godward foundation for accountability includes:', type: 'multiple_choice' as const, options: ['A) Managing optics', 'B) Reverent awe, confession, and surrender', 'C) Endless availability', 'D) Image-first decisions'], correctAnswer: 'B) Reverent awe, confession, and surrender', points: 1, orderIndex: 32 },
      { quizId: 212, question: 'Teaching accountability is strengthened by:', type: 'multiple_choice' as const, options: ['A) Skipping peer review', 'B) A sermon prep checklist and midweek feedback', 'C) Relying on memory for sources', 'D) Topic trends alone'], correctAnswer: 'B) A sermon prep checklist and midweek feedback', points: 1, orderIndex: 33 },
      { quizId: 212, question: 'Maxwell\'s Law of the Inner Circle advises you to:', type: 'multiple_choice' as const, options: ['A) Stay isolated', 'B) Prefer only fans', 'C) Choose truth-telling, loving teammates', 'D) Focus on public opinion'], correctAnswer: 'C) Choose truth-telling, loving teammates', points: 1, orderIndex: 34 },
      { quizId: 212, question: 'Financial and safety guardrails include:', type: 'multiple_choice' as const, options: ['A) One-person cash counts', 'B) Disappearing messages for privacy', 'C) Two-person counts, receipts, background checks, two-adult rule', 'D) No written policies'], correctAnswer: 'C) Two-person counts, receipts, background checks, two-adult rule', points: 1, orderIndex: 35 },
      { quizId: 212, question: 'Healthy digital communication practice:', type: 'multiple_choice' as const, options: ['A) Late-night private DMs', 'B) Disappearing message threads', 'C) Group-based channels, copy a second adult/parent when private is needed', 'D) Personal accounts for ministry'], correctAnswer: 'C) Group-based channels, copy a second adult/parent when private is needed', points: 1, orderIndex: 36 },
      { quizId: 212, question: 'When a leader fails, first faithful step is:', type: 'multiple_choice' as const, options: ['A) Minimize it', 'B) Hide it', 'C) Surface the issue quickly and tell the truth plainly', 'D) Shift blame'], correctAnswer: 'C) Surface the issue quickly and tell the truth plainly', points: 1, orderIndex: 37 },
      { quizId: 212, question: 'Burnout prevention relies on:', type: 'multiple_choice' as const, options: ['A) 24/7 availability', 'B) Canceling rest during busy seasons', 'C) Day off, nightly cut-offs, mentoring, and honest check-ins', 'D) Doubling event load'], correctAnswer: 'C) Day off, nightly cut-offs, mentoring, and honest check-ins', points: 1, orderIndex: 38 },
      { quizId: 212, question: 'Making accountability visible to parents includes:', type: 'multiple_choice' as const, options: ['A) Avoiding Q&A', 'B) Sharing safety policies, introducing leaders, explaining screening', 'C) Focusing only on events', 'D) Limiting parent access'], correctAnswer: 'B) Sharing safety policies, introducing leaders, explaining screening', points: 1, orderIndex: 39 },
      { quizId: 212, question: 'A wise boundary for counseling students is to:', type: 'multiple_choice' as const, options: ['A) Promise absolute confidentiality', 'B) Exclude parents in all cases', 'C) Listen, pray, document briefly, and refer when needed', 'D) Share details broadly for advice'], correctAnswer: 'C) Listen, pray, document briefly, and refer when needed', points: 1, orderIndex: 40 },
      { quizId: 212, question: 'The central goal of outreach is to:', type: 'multiple_choice' as const, options: ['A) Grow crowds', 'B) Win games', 'C) Make disciples who follow and obey Jesus', 'D) Trend online'], correctAnswer: 'C) Make disciples who follow and obey Jesus', points: 1, orderIndex: 41 },
      { quizId: 212, question: 'A clear gospel emphasizes:', type: 'multiple_choice' as const, options: ['A) Try harder', 'B) Self-improvement', 'C) Repentance and faith in Jesus who lived, died, and rose', 'D) Religious performance'], correctAnswer: 'C) Repentance and faith in Jesus who lived, died, and rose', points: 1, orderIndex: 42 },
      { quizId: 212, question: 'First 48-hour follow-up best practice:', type: 'multiple_choice' as const, options: ['A) Long survey', 'B) Wait for them to return', 'C) Personal student text and warm parent email with a next step', 'D) Mass newsletter only'], correctAnswer: 'C) Personal student text and warm parent email with a next step', points: 1, orderIndex: 43 },
      { quizId: 212, question: 'A simple pathway from guest to disciple-maker should be:', type: 'multiple_choice' as const, options: ['A) Complex and hard to explain', 'B) Event-heavy only', 'C) Clear and scalable: connect, belong, believe/become, build others', 'D) Unwritten and intuitive'], correctAnswer: 'C) Clear and scalable: connect, belong, believe/become, build others', points: 1, orderIndex: 44 },
      { quizId: 212, question: 'An invite culture grows when:', type: 'multiple_choice' as const, options: ['A) Leaders outsource invites', 'B) Giveaways drive everything', 'C) Leaders model prayer-invest-invite-include and celebrate attempts', 'D) Invites are kept private'], correctAnswer: 'C) Leaders model prayer-invest-invite-include and celebrate attempts', points: 1, orderIndex: 45 },
      { quizId: 212, question: 'Evangelistically clear preaching includes:', type: 'multiple_choice' as const, options: ['A) Five big ideas', 'B) Humor first', 'C) One clear text-driven big idea and a specific call to respond', 'D) No applications'], correctAnswer: 'C) One clear text-driven big idea and a specific call to respond', points: 1, orderIndex: 46 },
      { quizId: 212, question: 'A seeker-friendly environment could be:', type: 'multiple_choice' as const, options: ['A) Debate night', 'B) Alpha-style table with food, video, open Q&A', 'C) Unstructured hangout', 'D) Policy lecture'], correctAnswer: 'B) Alpha-style table with food, video, open Q&A', points: 1, orderIndex: 47 },
      { quizId: 212, question: 'Equipping students to witness begins with:', type: 'multiple_choice' as const, options: ['A) Ten-point essays', 'B) Only online posting', 'C) A three-minute testimony and a simple gospel tool (e.g., 3 circles)', 'D) Waiting until adulthood'], correctAnswer: 'C) A three-minute testimony and a simple gospel tool (e.g., 3 circles)', points: 1, orderIndex: 48 },
      { quizId: 212, question: 'Solid first steps for new believers include:', type: 'multiple_choice' as const, options: ['A) Delaying group for a year', 'B) Only attending events', 'C) Baptism process, simple Bible plan, small group, serving soon', 'D) Immediate leadership roles'], correctAnswer: 'C) Baptism process, simple Bible plan, small group, serving soon', points: 1, orderIndex: 49 },
      { quizId: 212, question: 'The ultimate power for Christian witness is:', type: 'multiple_choice' as const, options: ['A) Perfect arguments', 'B) Event excellence', 'C) Peer approval', 'D) The Holy Spirit empowering believers'], correctAnswer: 'D) The Holy Spirit empowering believers', points: 1, orderIndex: 50 }
    ];
    
    await db.insert(quizQuestions).values(questions);
    
    console.log(`Successfully created Youth Ministry Final Exam with ${questions.length} questions!`);
    console.log(`Quiz ID: ${quiz.id}`);
    console.log(`Access at: http://localhost:56000/quiz/youth-ministry-final-exam`);
    
    process.exit(0);
  } catch (error) {
    console.error('Error creating Youth Ministry Final Exam:', error);
    process.exit(1);
  }
}

addYouthMinistryFinalExam();
